user/urls.py
from django.urls import path
from user.views import EmployeeListView, load_hierarchy, EmployeesListView, load_employee_list, UserSignInView, \
    UserLogoutView, ProfileView, ProfileUpdateView, ProfileDeleteView, ajax_supervisors

urlpatterns = [
    path('', EmployeeListView.as_view(), name='home'),
    path('load_hierarchy/<int:employee_id>/', load_hierarchy, name='load_hierarchy'),
    path('employees/', EmployeesListView.as_view(), name='employees'),
    path('load_employee_list/', load_employee_list, name='load_employee_list'),
    path("login/", UserSignInView.as_view(), name="sign-in"),
    path("logout/", UserLogoutView.as_view(), name="logout"),
    path("profile/<int:pk>/", ProfileView.as_view(), name="profile"),
    path('employees/<int:pk>/update/', ProfileUpdateView.as_view(), name='employee_update'),
    path('employees/<int:pk>/delete/', ProfileDeleteView.as_view(), name='employee_delete'),
    path('ajax/supervisors/', ajax_supervisors, name='ajax_supervisors'),

]

website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
]

user/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class Employee(AbstractUser):
    """
    Custom user model representing an employee in the organization.

    Attributes:
        full_name (str): The full name of the employee.
        position (str): The position or job title of the employee.
        hire_date (Date): The date when the employee was hired.
        supervisor (Employee): The supervisor of the employee, represented as a foreign key to itself.
        level (int): The level or hierarchy position of the employee.

    Methods:
        __str__: Returns the full name of the employee when the object is converted to a string.

    Meta:
        ordering: Orders the employees based on their hierarchy level.
    """

    full_name = models.CharField(max_length=255)
    position = models.CharField(max_length=100)
    hire_date = models.DateField(null=True, blank=True)
    supervisor = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)
    level = models.IntegerField(null=True, blank=True)

    def __str__(self):
        """Return the full name of the employee when the object is converted to a string."""
        return self.full_name

    class Meta:
        """Meta options for the Employee model."""
        ordering = ['level']

templates/base.html
<html lang="en" class="">
<link type="text/css" id="dark-mode" rel="stylesheet" href="">
<style type="text/css" id="dark-mode-сustom-style"></style>
<style type="text/css" id="dark-mode-theme-changer-style"></style>
<head>
    {% load static %}
    <meta charset="utf-8">
    <title>Bootstrap, from Twitter</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="{% static 'css/bootstrap.css' %} " rel="stylesheet">
    <style>
        body {
          padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
        }
    </style>

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="https://cdn.jsdelivr.net/npm/html5shiv@3.7.3/dist/html5shiv.min.js"></script>
    <![endif]-->


</head>

<body>

<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <div class="nav-collapse">
                <ul class="nav">
                    <li><a href="{% url 'home' %}">Home</a></li>
                    <li><a href="{% url 'employees' %}">Employees</a></li>
                    {% if request.user.is_authenticated %}
                    <li><a href="{% url 'profile' pk=request.user.pk %}">{{ request.user.full_name }}</a></li>
                    <li><a href="{%url 'logout' %}" >Выйти</a></li>
                    {% else %}
                    <li><a href="{%url 'sign-in' %}" >Войти</a></li>
                    {% endif %}

                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </div>
</div>

<div class="container">
    {% block content %}


    {% endblock content %}

    <!-- JavaScript-код для обробки кліків та виклику Ajax -->
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>


    </script>
</div> <!-- /container -->

<!-- Le javascript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{% static 'js/bootstrap.js' %}"></script>


</body>
</html>

templates/employee.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


        {% for employee in page_obj %}
        <h4>
            <span class="employee" data-employee-id="{{ employee.id }}">
        {{ employee.full_name }}, ({{ employee.employee_set.all.count }})
    </span>
        </h4>

{% endfor %}

<!-- JavaScript-код для обробки кліків та виклику Ajax -->
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script src="{% static 'employee.js' %}">



</script>
{% endblock %}

templates/employee_list_partial.html
{% for employee in employees %}
  <p>{{ employee.full_name }} - {{ employee.position }} - {{ employee.email }} - {{ employee.hire_date }} - {{ employee.level }} lvl - {{employee.supervisor}}</p>
{% endfor %}

templates/employees.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<form id="employee-sort-form" method="get">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
</form>

<div id="employee-list">
    {% include 'employee_list_partial.html' %}
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="{% static 'employees_search_and_sort.js' %}"></script>
{% endblock %}